export const products = [
  {
    id: 1,
    img: '/images/previews/breaking-bad.png',
    link: 'https://github.com/Hassan-abdellah/react-with-breaking-bad-api',
    cats: ['2'],
  },
  {
    id: 2,
    img: '/images/previews/movie-api.png',
    link: 'https://github.com/Hassan-abdellah/react-movie-app',
    cats: ['2'],
  },
  {
    id: 3,
    img: '/images/previews/design-agency.png',
    link: 'https://github.com/Hassan-abdellah/design-agency-landing-page',
    cats: ['0'],
  },
  {
    id: 4,
    img: '/images/previews/url-shortener.png',
    link: 'https://github.com/Hassan-abdellah/link-shortener-api-landing-page',
    cats: ['2'],
  },
  {
    id: 5,
    img: '/images/previews/Instagram.png',
    link: 'https://github.com/Hassan-abdellah/tailwind-react-instagram-clone',
    cats: ['1'],
  },
  {
    id: 6,
    img: '/images/previews/image-gallery-tialwind.png',
    link: 'https://github.com/Hassan-abdellah/tailwind-react-image-gallery',
    cats: ['1', '2'],
  },
  {
    id: 7,
    img: '/images/previews/Delivery-App2.png',
    link: 'https://github.com/Hassan-abdellah/react-delivery-app',
    cats: ['0'],
  },
  {
    id: 8,
    img: '/images/previews/qwery.png',
    link: 'https://github.com/Hassan-abdellah/Qwery-Travel-Landing-Page',
    cats: ['4'],
  },
  // {
  //   id: 9,
  //   img: '/images/previews/to-do-app.png',
  //   link: 'https://github.com/Hassan-abdellah/react-to-do-list-application',
  //   cats: ['3'],
  // },
  // {
  //   id: 10,
  //   img: '/images/previews/twitter-sidebar.png',
  //   link: 'https://github.com/Hassan-abdellah/react-twitter-sidebar',
  //   cats: ['3'],
  // },
  // {
  //   id: 11,
  //   img: '/images/previews/Login.png',
  //   link: 'https://github.com/Hassan-abdellah/',
  //   cats: ['3'],
  // },
  // {
  //   id: 12,
  //   img: '/images/previews/social-auth.png',
  //   link: 'https://github.com/Hassan-abdellah/',
  //   cats: ['3'],
  // },
  {
    id: 13,
    img: '/images/previews/photographer-preview.png',
    link: 'https://kevinphotographer.netlify.app/',
    cats: ['1', '4'],
  },
  {
    id: 14,
    img: '/images/previews/countries-api.png',
    link: 'https://whereisinworld.netlify.app/',
    cats: ['2'],
  },
  {
    id: 15,
    img: '/images/previews/app-modern.png',
    link: 'https://modernapp.netlify.app/',
    cats: ['0'],
  },
  {
    id: 16,
    img: '/images/previews/bookmark.jpg',
    link: 'https://bookybookmarkmanager.netlify.app/',
    cats: ['0'],
  },
  {
    id: 17,
    img: '/images/previews/clipboard.jpg',
    link: 'https://clippyclipboard.netlify.app/',
    cats: ['0'],
  },
  {
    id: 18,
    img: '/images/previews/fylo.jpg',
    link: 'https://flyofilemanager.netlify.app/',
    cats: ['0'],
  },
];

export const categories = [
  { id: 1, code: '0', name: 'Landing Pages' },
  { id: 2, code: '1', name: 'Tailwind' },
  { id: 3, code: '2', name: 'API Intgeration' },
  // { id: 4, code: '3', name: 'Components' },
  { id: 5, code: '4', name: 'Covnert Figma' },
];

export const skills = [
  { id: 1, name: 'ReactJS', image: '/images/skills/react.svg' },
  { id: 2, name: 'HTML', image: '/images/skills/html.svg' },
  { id: 3, name: 'Linux', image: '/images/skills/linux.svg' },
  { id: 4, name: 'Postman', image: '/images/skills/postman.svg' },
  { id: 5, name: 'MongoDB', image: '/images/skills/mongodb.svg' },
  { id: 6, name: 'Javascript', image: '/images/skills/js.svg' },
  { id: 7, name: 'NodeJS', image: '/images/skills/nodejs.svg' },
  { id: 8, name: 'Git', image: '/images/skills/git.svg' },
  { id: 9, name: 'Github', image: '/images/skills/github.svg' },
  { id: 10, name: 'CSS', image: '/images/skills/css3.svg' },
  { id: 11, name: 'TailwindCSS', image: '/images/skills/tailwindcss.svg' },
  { id: 12, name: 'Figma', image: '/images/skills/figma.svg' },
  { id: 13, name: 'ExpressJS', image: '/images/skills/express.svg' },
  { id: 14, name: 'Firebase', image: '/images/skills/firebase.svg' },
  { id: 15, name: 'Sass', image: '/images/skills/sass.svg' },
  { id: 16, name: 'Next JS', image: '/images/skills/nextjs.svg' },
];
